project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    left: 
      - text: "Hands-on Exercise"
        menu: 
          - text: "Hands-on 1: Geospatial Data Wrangling"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on 2: Choropleth Mapping with tmap"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "Hands-on 3: 1st Order Spatial Point Patterns Analysis"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
          - text: "Hands-on 4: 2nd Order Spatial Point Patterns Analysis"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_P2.html"
          - text: "Hands-on 5: Spatial Weights and Applications"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"
          - text: "Hands-on 6: Measures of Global and Local Spatial Association"
            href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
          - text: "Hands-on 7: Geographic Segmentation with Spatially Constrained Cluster Analysis"
            href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html"
          - text: "Hands-on 8: Geographically Weighted Regression"
            href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html"
          
            
      - text: "In-class Exercise"
        menu: 
          - text: "ICE 1: Data Wrangling with Nigeria Water Point Data"
            href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html"
          - text: "ICE 2: Analytical Mapping"
            href: "In-class_Ex/In-class_Ex03/In-class_Ex03.html"
          - text: "ICE 3: 1st Order Spatial Point Pattern Analysis"
            href: "In-class_Ex/In-class_Ex04/In-class_Ex04.html"
          - text: "ICE 4: Advanced Spatial Point Pattern Analysis"
            href: "In-class_Ex/In-class_Ex05/In-class_Ex05.html"
          - text: "ICE 5: Spatial Weights and Applications"
            href: "In-class_Ex/In-class_Ex06/In-class_Ex06.html"
          - text: "ICE 6: Global and Local Measures of Autocorrelation"
            href: "In-class_Ex/In-class_Ex07/In-class_Ex07.html"
          - text: "ICE 7: "
            href: "In-class_Ex/In-class_Ex08/In-class_Ex08.html"
          - text: "ICE 8: "
            href: "In-class_Ex/In-class_Ex09/In-class_Ex09.html"
          - text: "ICE 9: "
            href: "In-class_Ex/In-class_Ex10/In-class_Ex10.html"
          - text: "ICE 10: "
            href: "In-class_Ex/In-class_Ex11/In-class_Ex11.html"
          
      - text: "Take Home Exercise"
        menu: 
          - text: "Take Home Exercise 1"
            href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
          - text: "Take Home Exercise 2"
            href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html"
          - text: "Take Home Exercise 3"
            href: "Take-home_Ex/Take-home_Ex03/Take-home_Ex03.html"
    #right:
     # - href: index.qmd
      #  text: Home
      #- about.qmd

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual

